CREATE USER pipeline WITH ENCRYPTED PASSWORD '${password}';

CREATE DATABASE pipeline;

\c pipeline

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO pipeline;

\c cicd

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO pipeline;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO pipeline;
GRANT ALL PRIVILEGES ON DATABASE cicd TO pipeline;

-- https://dba.stackexchange.com/a/74578

ALTER DEFAULT PRIVILEGES FOR ROLE cicd IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO pipeline;
ALTER DEFAULT PRIVILEGES FOR ROLE cicd IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO pipeline;
